name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - uses: snok/install-poetry@v1
      with:
        version: 1.2.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Lint
      run: make lint
      if: ${{ matrix.python-version == "3.8" && matrix.os == "ubuntu-latest" }}
      
    - name: Test
      run: make test

    - name: Doc
      run: make doc
      if: ${{ matrix.python-version == "3.8" && matrix.os == "ubuntu-latest" }}
