name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - uses: snok/install-poetry@v1
      with:
        version: 1.2.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Lint
      run: make lint
    
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: snok/install-poetry@v1
      with:
        version: 1.2.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Test
      run: make test

  doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - uses: snok/install-poetry@v1
      with:
        version: 1.2.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Doc
      run: make doc

    - name: Publish doc
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .meta/docs
        token: ${{ secrets.REPO_TOKEN }}
      if: ${{ github.ref == 'refs/heads/main' }}
